### PR TITLE
Encoding selector for fabricechapuis

### LINKED ISSUE #288: Implement EncodingSelector by fabricechapuis

### PR DESCRIPTION
**Pull request by fabricechapuis**
Closes #288 
Please accept this [PR ](https://github.com/HEIGVD-Course-DAI/dai-lab-fileio-B/pull/154) and [this one](https://github.com/HEIGVD-Course-DAI/dai-lab-fileio-B/pull/233) before looking at this PR.

### CODE REVIEW

**Comment by jehrensb** [comment]
Your PR contains too many files. If you only implemented the Encoding selector, it should only contain this file and its test file.

**Comment by fabricechapuis** [comment]
> Your PR contains too many files. If you only implemented the Encoding selector, it should only contain this file and its test file.

The files that shouldn't be here won't be in the PR anymore once the PR I mentionned clearly in the comment will be merged, since git compares the content of the source branch and the target branch. by merging the FIRST PR I did, as said in the previous comment, the files will disappear from this PR automatically.
@jehrensb

**Comment by jehrensb** [comment]
Of course the files won't cause any problem, since you based the new branch on your existing branch.

But you still have to submit a clean pull request which contains only the required files, nothing else.

**Comment by jehrensb** [comment]
Please submit a clean pull request which contains only the required files, nothing else.

**Pull request closed without merging**
